### ISSUE TITLE
GUI server breaks if derivations is not defined in yaml  

### ISSUE THREAD

**Issue by robschneider16** [NASA-AMMOS/AIT-Core#155]
This was discovered when trying to upgrade OCO3 repo from 1.2.0 to 1.4.0. OCO3 did not have derivations defined in the streams yaml. Server should not assume derivations is always defined.

`
Traceback (most recent call last):
  File "/home/rschneid/.virtualenvs/oco3/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/rschneid/.virtualenvs/oco3/lib/python2.7/site-packages/gevent/util.py", line 49, in __call__
    return func(*args, **kwargs)
  File "/home/rschneid/.virtualenvs/oco3/lib/python2.7/site-packages/ait/gui/__init__.py", line 406, in telem_handler
    v = decoded._getattr(field)
  File "/home/rschneid/.virtualenvs/oco3/lib/python2.7/site-packages/ait/core/tlm.py", line 487, in _getattr
    if fieldname in self._defn.derivationmap:
TypeError: argument of type 'NoneType' is not iterable
<Greenlet at 0x7fdde3963870: telem_handler(<ait.gui.Session object at 0x7fdde8ef8850>)> failed with TypeError
`

**Comment by aywaldron** [comment]
@robschneider16 Can I get some more details on the configuration (server and tlm) used to get this error? I am unable to duplicate with the example `Ethernet_HS_Packet` which does not contain derivations (linked below).

https://github.com/NASA-AMMOS/AIT-Core/blob/abc15691cbe5b2299d80d56712bca59e6f2db825/config/tlm.yaml#L46
