### ISSUE TITLE
Update struct.pack usage when passing string as data

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#236]
While testing the UI-plugin, we saw the following error message when sending a command with string argument (which passed frontend validation): 

```
Traceback (most recent call last):
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/bottle.py", line 1742, in wrapper
    rv = callback(*a, **ka)
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/ait/gui/__init__.py", line 314, in handle
    if self.send(name, *args):
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/ait/gui/__init__.py", line 397, in send
    encoded = cmdobj.encode()
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/ait/core/cmd.py", line 253, in encode
    encoded[defn.slice(offset)] = defn.encode(value)
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/ait/core/cmd.py", line 116, in encode
    return self.type.encode(value) if self.type else bytearray()
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/venv/lib/python3.7/site-packages/ait/core/dtype.py", line 251, in encode
    as_str = struct.pack(self.format, fvalue)
struct.error: argument for 's' must be a bytes object
```
In python 2, strings were essentially bytes, but in python 3, they are different.  Since struct.pack expects bytes, anytime it is passed a string type, that type should be converted to bytes (i.e.  strobj.encode())

**Comment by MJJoyce** [comment]
Resolved in #259
