### ISSUE TITLE
AIT bin tests (Command): ait_cmd_hist, ait_cmd_send

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#256]
This issue will track the testing and resulting issues related to Python3 and the Command bin scripts.

**Comment by nttoole** [comment]
AIT Command:

** ait_cmd_hist.py

Status: Failed->Fixes Applied->Pass

Pcap file: /Users/nttoole/dev/ait/git_repos/ait_020720/cmdhist.pcap


Running script and ERROR:
[venv] MT-202661{nttoole}% ./ait_cmd_hist.py $PCAP
  File "./ait_cmd_hist.py", line 29
    //print(header.timestamp.strftime('%Y-%m-%d %H:%M:%S') + '\t' + data.decode())
     ^
SyntaxError: invalid syntax
[venv] MT-202661{nttoole}% vi ait_cmd_hist.py
[venv] MT-202661{nttoole}% ./ait_cmd_hist.py $PCAP
2020-02-25T16:49:29.633 | WARNING  | AIT_ROOT not set.  Defaulting to "/Users/nttoole/Development/ait/git_repos/ait_020720/AIT-Core/ait/core/bin"
. . .
2020-02-25T16:49:29.846 | PROGRAM  | ./ait_cmd_hist.py /Users/nttoole/dev/ait/git_repos/ait_020720/cmdhist.pcap
Traceback (most recent call last):
  File "./ait_cmd_hist.py", line 34, in <module>
    main()
  File "./ait_cmd_hist.py", line 28, in main
    print(header.timestamp.strftime('%Y-%m-%d %H:%M:%S') + '\t' + data)
TypeError: can only concatenate str (not "bytes") to str


Proposed Fix:
-            print(header.timestamp.strftime('%Y-%m-%d %H:%M:%S') + '\t' + data)
+            print(header.timestamp.strftime('%Y-%m-%d %H:%M:%S') + '\t' + data.decode())


Issue #: 





=================


** ait_cmd_send.py

Status: Pass

[venv] MT-202661{nttoole}% ./ait_cmd_send.py SEND_STR_ARG 1
2020-02-25T17:45:33.258 | WARNING  | AIT_ROOT not set.  Defaulting to "/Users/nttoole/Development/ait/git_repos/ait_020720/AIT-Core/ait/core/bin"
. . .
2020-02-25T17:45:33.502 | PROGRAM  | ./ait_cmd_send.py SEND_STR_ARG 1
2020-02-25T17:45:33.505 | COMMAND  | Sending to 127.0.0.1:3075: SEND_STR_ARG 1
2020-02-25T17:45:33.507 | PROGRAM  | done.
[venv] MT-202661{nttoole}% SEQ_ENABLE_DISABLE 21 ENABLED
SEQ_ENABLE_DISABLE: Command not found.
[venv] MT-202661{nttoole}% ./ait_cmd_send.py SEQ_ENABLE_DISABLE 21 ENABLED
2020-02-25T17:47:03.444 | WARNING  | AIT_ROOT not set.  Defaulting to "/Users/nttoole/Development/ait/git_repos/ait_020720/AIT-Core/ait/core/bin"
. . .
2020-02-25T17:47:03.729 | COMMAND  | Sending to 127.0.0.1:3075: SEQ_ENABLE_DISABLE 21 ENABLED
2020-02-25T17:47:03.730 | PROGRAM  | done.
