### ISSUE TITLE
AIT bin tests (Table): ait_table_decode, ait_table_encode

### ISSUE THREAD

**Issue by nttoole** [NASA-AMMOS/AIT-Core#257]
This issue will track the testing and resulting issues related to Python3 and the Table bin scripts.

**Comment by nttoole** [comment]
AIT Table:

Status: Failed->Fixes Applied->Pass

03.11.20:  Received test data from Rob, including input: tabledict, data-input, table-name.

**ait_table_decode.py**


[venv] MT-202661{nttoole}% ./AIT-Core/ait/core/bin/ait_table_decode.py --tabletype schedule --fswtabdict data/sample_table.yaml --binfile data/output/ait-schedule.bin
2020-03-17T13:39:04.975 | WARNING  | AIT_ROOT not set.  Defaulting to "/Users/nttoole/Development/ait/git_repos/ait_020720"
…
2020-03-17T13:39:05.398 | PROGRAM  | ./AIT-Core/ait/core/bin/ait_table_decode.py --tabletype schedule --fswtabdict data/sample_table.yaml --binfile data/output/ait-schedule.bin
DEBUG: dictpath = data/sample_table.yaml
DEBUG: tabletype = schedule
DEBUG: binfiledata/output/ait-schedule.bin
DEBUG: fswtabdict location /Users/nttoole/dev/ait/git_repos/ait_020720/AIT-Core/config/table.yaml
TABLE type: None
TABLE version: 0
TABLE definition: None
Traceback (most recent call last):
  File "./AIT-Core/ait/core/bin/ait_table_decode.py", line 84, in <module>
    main()
  File "./AIT-Core/ait/core/bin/ait_table_decode.py", line 78, in main
    table.writeToText(fswtabdict, tabletype, binfile, verbose, version)
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/AIT-Core/ait/core/table.py", line 667, in writeToText
    fswtabdefn.toText(stream,fswtab_f,verbose,version)
AttributeError: 'NoneType' object has no attribute 'toText'


ISSUES:
1) script is ALWAYS using the default table dict, ignore the value passed in
Fix: update code to be consistent with the encode case, use the passed in value if supplied.
Actually had to fix both scripts to handle the user-option-then-default-fswtabdict logic.

===========

**ait_table_encode.py**

[venv] MT-202661{nttoole}% ./AIT-Core/ait/core/bin/ait_table_encode.py --tabfile data/schedule_table.txt --fswtabdict data/sample_table.yaml --tabletype schedule --binfile /tmp/ait-schedule.bin
2020-03-17T11:19:32.501 | WARNING  | AIT_ROOT not set.  Defaulting to "/Users/nttoole/Development/ait/git_repos/ait_020720"
…
2020-03-17T11:19:32.820 | PROGRAM  | ./AIT-Core/ait/core/bin/ait_table_encode.py --tabfile data/schedule_table.txt --fswtabdict data/sample_table.yaml --tabletype schedule --binfile /tmp/ait-schedule.bin
Traceback (most recent call last):
  File "./AIT-Core/ait/core/bin/ait_table_encode.py", line 76, in <module>
    main()
  File "./AIT-Core/ait/core/bin/ait_table_encode.py", line 70, in main
    table.writeToBinary(fswtabdict, tabletype, tabfile, verbose, outbin=args.binfile)
  File "/Users/nttoole/Development/ait/git_repos/ait_020720/AIT-Core/ait/core/table.py", line 709, in writeToBinary
    log.info("Generating binary: %s" % outbin)
NameError: name 'log' is not defined


ISSUES:
1) table.py uses log without importing it.
fix: Import log

**Comment by nttoole** [comment]
Some test PCAP files:
[pcap_files.zip](https://github.com/NASA-AMMOS/AIT-Core/files/4418008/pcap_files.zip)

**Comment by MJJoyce** [comment]
Fixed in #259
