### ISSUE TITLE
Command Encoding Issue

### ISSUE THREAD

**Issue by cjjacks** [NASA-AMMOS/AIT-Core#534]
Valid commands can sometime fail encoding. For example:

```
!Command
name: TORQUER_ALL_PERCENT_ON_CC
opcode: 0x41
subsystem: Structure
desc: Generic_torquer All Percent On Command
arguments:
  - !Fixed
    name: CCSDS_STREAMID
    desc: CCSDS Packet Identification
    type: MSB_U16
    value: 0x193a
  - !Fixed
    name: CCSDS_SEQUENCE
    desc: CCSDS Packet Sequence Control
    type: MSB_U16
    value: 0xc000
  - !Fixed
    name: CCSDS_LENGTH
    desc: CCSDS Packet Data Length
    type: MSB_U16
    value: 7
  - !Fixed
    name: CCSDS_FC
    desc: CCSDS Command Function Code
    type: U8
    value: 5
  - !Fixed
    name: CCSDS_CHECKSUM
    desc: CCSDS Command Checksum
    type: U8
    value: 0
  - !Argument
    name:  DIRECTION_0
    desc:  Direction - 0
    units: none
    range: [0,1]
    type:  U8
  - !Argument
    name:  PERCENT_ON_0
    desc:  Percent On - 0
    units: none
    range: [0,100]
    type:  U8
  - !Argument
    name:  DIRECTION_1
    desc:  Direction - 1
    units: none
    range: [0,1]
    type:  U8
  - !Argument
    name:  PERCENT_ON_1
    desc:  Percent On - 1
    units: none
    range: [0,100]
    type:  U8
  - !Argument
    name:  DIRECTION_2
    desc:  Direction - 2
    units: none
    range: [0,1]
    type:  U8
  - !Argument
    name:  PERCENT_ON_2
    desc:  Percent On - 2
    units: none
    range: [0,100]
    type:  U8
```

```
>>> cmddict = ait.core.cmd.getDefaultDict()
>>> cmd = cmddict.create("TORQUER_ALL_PERCENT_ON_CC",*[0,0,0,0,0,0])
>>> cmd.validate()
True
>>> cmd.encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cameron/ttc/gsw-ait/gswait/cmd/cfs_cmd.py", line 70, in encode
    encoded[defn.slice(offset)] = defn.encode(value)
  File "/Users/cameron/ttc/gsw-ait/.venv/lib/python3.9/site-packages/ait/core/cmd.py", line 144, in slice
    start = self.bytes[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cjjacks** [comment]
correct traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cameron/ttc/gsw-ait/.venv/lib/python3.9/site-packages/ait/core/cmd.py", line 274, in encode
    encoded[defn.slice(offset)] = defn.encode(value)
  File "/Users/cameron/ttc/gsw-ait/.venv/lib/python3.9/site-packages/ait/core/cmd.py", line 144, in slice
    start = self.bytes[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by cjjacks** [comment]
I believe the issue is because I was defining the bytes field which is indeed required. Here is the correct defn:

```
!Command
name: TORQUER_ALL_PERCENT_ON_CC
opcode: 0x41
subsystem: Structure
desc: Generic_torquer All Percent On Command
arguments:
  - !Fixed
    name: CCSDS_STREAMID
    desc: CCSDS Packet Identification
    type: MSB_U16
    bytes: [0,1]
    value: 0x193a
  - !Fixed
    name: CCSDS_SEQUENCE
    desc: CCSDS Packet Sequence Control
    type: MSB_U16
    bytes: [2,3]
    value: 0xc000
  - !Fixed
    name: CCSDS_LENGTH
    desc: CCSDS Packet Data Length
    type: MSB_U16
    bytes: [4,5]
    value: 7
  - !Fixed
    name: CCSDS_FC
    desc: CCSDS Command Function Code
    type: U8
    bytes: 6
    value: 5
  - !Fixed
    name: CCSDS_CHECKSUM
    desc: CCSDS Command Checksum
    type: U8
    bytes: 7
    value: 0
  - !Argument
    name:  DIRECTION_0
    desc:  Direction - 0
    units: none
    bytes: 8
    range: [0,1]
    type:  U8
  - !Argument
    name:  PERCENT_ON_0
    desc:  Percent On - 0
    units: none
    bytes: 9
    range: [0,100]
    type:  U8
  - !Argument
    name:  DIRECTION_1
    desc:  Direction - 1
    units: none
    range: [0,1]
    bytes: 10
    type:  U8
  - !Argument
    name:  PERCENT_ON_1
    desc:  Percent On - 1
    units: none
    range: [0,100]
    bytes: 11
    type:  U8
  - !Argument
    name:  DIRECTION_2
    desc:  Direction - 2
    units: none
    range: [0,1]
    bytes: 12
    type:  U8
  - !Argument
    name:  PERCENT_ON_2
    desc:  Percent On - 2
    units: none
    range: [0,100]
    bytes: 13
    type:  U8
```

```
cmd = cmddict.create("TORQUER_ALL_PERCENT_ON_CC",*[0,0,0,0,0,0])
>>> cmd.encode()
bytearray(b'\x00A\x0e\x19:\xc0\x00\x00\x07\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
```
