### ISSUE TITLE
Command silent failure when providing a number when string is expected

### ISSUE THREAD

**Issue by MJJoyce** [NASA-AMMOS/AIT-Core#66]
Per @lorsposto                 

`bliss-cmd-send` fails silently when a command is provided a number argument when a string is expected. The command fails validation but no messages are returned, so the user is not informed about what went wrong. 

Sample command with one string argument:
```
- !Command
  name:      TEST_CMD
  opcode:    0x0000
  subsystem: CORE
  title: Test cmd
  desc:  Test cmd

  arguments:
    - !Argument
      name:  arg1
      desc:  Arg 1
      units: none
      type:  S16
      bytes: [0,15]
```

Sending the command:
```
>> bliss-cmd-send TEST_CMD 1
2018-03-22T09:02:19.995 | PROGRAM  | /Users/lsposto/.virtualenvs/ait/bin/bliss-cmd-send TEST_CMD 1
2018-03-22T09:02:19.998 | PROGRAM  | done.
```
Demonstrating the lack of validation messages. The problem is apparent after trying to encode the command anyway:
```
>>> import bliss.core.cmd
>>> cmddict = bliss.core.cmd.getDefaultCmdDict()
>>> cmdobj = cmddict.create('TEST_CMD', 1)
>>> messages = []
>>> cmdobj.validate(messages)
False
>>> messages
[]
>>> cmdobj.encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lsposto/.virtualenvs/ait/lib/python2.7/site-packages/bliss/core/cmd.py", line 252, in encode
    encoded[defn.slice(offset)] = defn.encode(value)
  File "/Users/lsposto/.virtualenvs/ait/lib/python2.7/site-packages/bliss/core/cmd.py", line 115, in encode
    return self.type.encode(value) if self.type else bytearray()
  File "/Users/lsposto/.virtualenvs/ait/lib/python2.7/site-packages/bliss/core/dtype.py", line 238, in encode
    return bytearray(struct.pack(self.format, value))
struct.error: argument for 's' must be a string
```

**Comment by MJJoyce** [comment]
Note, this is an older ticket which refers to `BLISS` instead of `AIT`. Still an issue either way =)
